[build]
  publish = "public"
  command = "node build.js"

# No redirect needed — admin folder is copied into public by build.js

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"